name: Repository dispatch receive

on:
  repository_dispatch:
    types: [on-demand-test]

jobs:
  receive-repository-dispatch:
    name: BuildAndRun
    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 180
    container: ros:${{ matrix.rosdistro }}
    env:
      DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: false
      matrix:
        rosdistro: [humble]
        runs_on: [ubuntu-22.04]
        cmake_build_type: [RelWithDebInfo, Release]
    
    steps:
      - name: Print Received Data
        run: |
          echo "Received Event Data:"
          echo "Ref: ${{ github.event.client_payload.ref }}"
          echo "Repo: ${{ github.event.client_payload.repo }}"

      - name: Checkout THIS Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: src/the_internal_repository
      
      - name: Checkout GET Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ github.event.client_payload.repo }}
          ref: ${{ github.event.client_payload.ref }}
          path: src/scenario_simulator_v2

      - name: Install dependencies
        run: |
          vcs import src < src/scenario_simulator_v2/dependency_${{ matrix.rosdistro }}.repos

      - name: Resolve rosdep and install colcon mixin
        run: |
          apt-get update
          apt-get install -y python3-pip python3-colcon-lcov-result lcov unzip gcovr
          rosdep update --include-eol-distros
          rosdep install -iy --from-paths src --rosdistro ${{ matrix.rosdistro }}
          colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
          colcon mixin update default
        shell: bash

      - name: Build
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          colcon build --symlink-install \
          --cmake-args \
            -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} \
            -DBUILD_CPP_MOCK_SCENARIOS=ON \
            -DBUILD_TESTING=true
        shell: bash

      - name: Colcon test
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          source install/local_setup.bash
          colcon test --event-handlers console_cohesion+
          colcon lcov-result
        shell: bash
