name: Repository dispatch receive

on:
  repository_dispatch:
    types: [on-demand-test]

jobs:
  receive-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Print Received Data
        run: |
          echo "Received Event Data:"
          echo "Ref: ${{ github.event.client_payload.ref }}"
          echo "Repo: ${{ github.event.client_payload.repo }}"

      - name: Checkout THIS Repository
        uses: actions/checkout@v4
        with:
          path: "owner_repo"
      
      - name: Checkout GET Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.repo }}
          ref: ${{ github.event.client_payload.ref }}
          path: "receive_repo"

      - name: show
        run: ls
