name: Repository dispatch receive

on:
  repository_dispatch:
    types: [on-demand-test]

jobs:
  receive-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Print Received Data
        run: |
          echo "Received Event Data:"
          echo "Ref: ${{ github.event.client_payload.ref }}"
          echo "Ref URL: ${{ github.event.client_payload.ref_url }}"

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: show
        run: ls
